# Generated by Django 6.0.3 on 2026-03-21 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSS_source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('feed_url', models.URLField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RSS_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.TextField(blank=True, null=True)),
                ('dedupe_key', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.TextField()),
                ('url', models.URLField(max_length=1000)),
                ('summary', models.TextField(blank=True, null=True)),
                ('raw_content', models.JSONField()),
                ('status', models.CharField(default='valid', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='crawler.rss_source')),
            ],
            options={
                'verbose_name_plural': 'RSS Entries',
                'ordering': ['-published_at'],
            },
        ),
    ]
